////This code was generated by a tool.
////Changes to this file will be lost if the code is regenerated.
//// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
//using System;
//using System.Data.SQLite;

//namespace ISBD
//{
//    public class SQLiteDb
//    {
//        string _path;
//        public SQLiteDb(string path)
//        {
//            _path = path;
//        }
        
//         public void Create()
//        {
//            using (SQLiteConnection db = new SQLiteConnection(_path))
//            {
//                db.CreateTable<Kategorie>();
//                db.CreateTable<Osoby>();
//                db.CreateTable<Symbole>();
//                db.CreateTable<Transakcje>();
//                db.CreateTable<Uprawnienia>();
//            }
//        }
//    }
//    public partial class Kategorie
//    {
//        [PrimaryKey, AutoIncrement]
//        public Int64 IdK { get; set; }
        
//        [Unique(Name = "sqlite_autoindex_Kategorie_1", Order = 0)]
//        [NotNull]
//        public String Nazwa { get; set; }
        
//        [NotNull]
//        public Int64 Rodzaj { get; set; }
        
//        public Int64? IdKRodzic { get; set; }
        
//        [NotNull]
//        public Int64 IdS { get; set; }
        
//    }
    
//    public partial class Osoby
//    {
//        [PrimaryKey, AutoIncrement]
//        public Int64 IdO { get; set; }
        
//        [NotNull]
//        public String Login { get; set; }
        
//        [NotNull]
//        public String Haslo { get; set; }
        
//        [NotNull]
//        public String Imie { get; set; }
        
//        public String Nazwisko { get; set; }
        
//        [NotNull]
//        public Int64 DataU { get; set; }
        
//    }
    
//    public partial class Symbole
//    {
//        [PrimaryKey, AutoIncrement]
//        public Int64 IdS { get; set; }
        
//        [NotNull]
//        public Int64 Kolor { get; set; }
        
//        public String Ikona { get; set; }
        
//    }
    
//    public partial class Transakcje
//    {
//        [PrimaryKey, AutoIncrement]
//        public Int64 IdT { get; set; }
        
//        [NotNull]
//        public Double Kwota { get; set; }
        
//        [NotNull]
//        public String Tytul { get; set; }
        
//        public String Opis { get; set; }
        
//        [NotNull]
//        public String Data { get; set; }
        
//        [NotNull]
//        public Int64 IdO { get; set; }
        
//        [NotNull]
//        public Int64 IdK { get; set; }
        
//    }
    
//    public partial class Uprawnienia
//    {
//        [PrimaryKey, AutoIncrement]
//        public Int64 IdU { get; set; }
        
//        [NotNull]
//        public Int64 Poziom { get; set; }
        
//        [NotNull]
//        public Int64 IdOBene { get; set; }
        
//        [NotNull]
//        public Int64 IdOD { get; set; }
        
//    }
    
//}
